services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000



  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes



  db:
    image: postgres:15
    environment:
      POSTGRES_DB: airjumper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
  

  consumer:
    build: .
    container_name: kafka-consumer
    depends_on:
      - db
      - kafka
    command: python -m consumer.kafka_consumer
    environment:
      - DB_URI=dbname=airjumper user=postgres password=secret host=db port=5432
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=airjumper-analytics
